#!/usr/bin/env node

fs  = require('fs');
pth = require('path');
yml = require('js-yaml');
req = require('request');
_   = require('underscore');



var FastDriver = function  (filename) {
  var _this = this;
  _this.filename = filename;
  _this.execQue  =[];
  
  _this.resolveFileName = function () {
    try {
      _this.fullFilePath = pth.resolve(_this.filename);
    }
    catch (err) {
      console.log("Could not find the specified file.");
      process.exit(1);
    }
  };

  _this.parseYAML = function () {
    try {
      _this.parsed = yml.safeLoad(fs.readFileSync(_this.fullFilePath, 'utf8'));
      console.log(doc);
    } catch (err) {
      console.log('Could not load yaml file: ' + err);
      process.exit(1);
    }
  };

  _this.resolveDeps = function () {
    
  };

  _this.run = function () {
    _this.resolveFileName();
    _this.parseYAML();
    _this.resolveDeps();
    _this.executeActions();
  }
};

var fd = new FastDriver(process.argv[2]);
fd.run();