#!/usr/bin/env node

'use strict';

var fs  = require('fs');
var pth = require('path');
var yml = require('js-yaml');
var req = require('request');
var _   = require('underscore');
var clc = require('cli-color');
var prg = require('progress');



var FastDriver = function  (filename) {
  var _this       = this;
  _this.filename  = filename;
  _this.groupDict = {};
  _this.execQue   = [];
  _this.baseUrl   = 'https://api.stackdriver.com/v0.2/groups';
  
  _this.resolveFileName = function () {
    try {
      _this.fullFilePath = pth.resolve(_this.filename);
    }
    catch (err) {
      console.log(clc.red("Could not find the specified file."));
      process.exit(1);
    }
  };

  _this.parseYAML = function () {
    try {
      _this.parsed = yml.safeLoad(fs.readFileSync(_this.fullFilePath, 'utf8'));
    } catch (err) {
      console.log(clc.red('Could not load yaml file: ' + err));
      process.exit(1);
    }
  };

  _this.extract_api_key = function () {
    try {
    _this.api_key = _this.parsed['stackdriver_api_key'];
    delete _this.parsed['stackdriver_api_key'];
    }
    catch (err) {
      console.log(clc.red(err));
    }
    if (!_this.api_key) {
      console.log(clc.red('stackdriver_api_key is not set in the spec file'));
      process.exit(1);
    }
  };

  _this.getGroupList = function () {
    var opts = {};
    opts.url = 'https://api.stackdriver.com/v0.2/groups'
    opts.headers = {'accept': 'application/json', 
                    'x-stackdriver-apikey': _this.api_key};
    return req(opts, function (err, resp, body) {
      if (!err) {
        _.each(body['data'], function (item) {
          _this.groupDict[item.name] = item.id;
        });
      }
      else {
        console.log(clc.red('An error ocurred while retrieving existing group list: ' + err));
        process.exit(1);
      }
    });
  };

  _this.resolveDeps = function () {
    ks = Object.keys(_this.parsed);
    _.each(ks, function (key) {
      group = _this.parsed[key];
      if (group.requires) {
        var parentGroup = _this.parsed[group.requires];
        _this.safePush({name: group.requires, obj: parentGroup});
      }
      else if (group.parent && !group.requires) {
        group.parent = _this.getParentId(group.parent);
      }
      _this.safePush({name: key, obj: group});
    });
  };

  // _this.processQue = function () {
  //   var opts = {
  //     'url': ''
  //   };

  // };

  // util functions
  _this.safePush = function (item) {
    if (!_this.isAlreadyInQueue(item.name)){
      _this.execQue.push(item);
    }
  };

  _this.isAlreadyInQueue = function (groupName) {
    var found = false;
    _.each(_this.execQue, function (item) {
      if (item.name === groupName) { 
        found = true;
      }
    });
    return found;
  };

  _this.getParentId = function (groupName) {
    return _this.groupDict[groupName];
  };
 
  // "main()"  
  _this.run = function () {
    _this.resolveFileName();
    _this.parseYAML();
    _this.extract_api_key();
    _this.getGroupList();
    _this.resolveDeps();
    _this.processQue();
  }
};

var fd = new FastDriver(process.argv[2]);
fd.run();